### PR TITLE
Improve Angles Rotation

### PR DESCRIPTION
**Pull request by Fronkln**
image

image

[usrc_angles.zip](https://github.com/lewa-j/Unity-Source-Tools/files/5764278/usrc_angles.zip)

### CODE REVIEW

**Comment by lewa-j** [comment]
`angles.y -= angles.y * 2;`
Isn't it identical to `angles.y = -angles.y;`?

**Comment by Fronkln** [comment]
> `angles.y -= angles.y * 2;`
> Isn't it identical to `angles.y = -angles.y;`?

Haven't checked because i was wrestling with the inconsistent editor values, gonna quickly see if it makes a difference then make a followup commit

**Comment by lewa-j** [comment]
If it is, then you can just remove minus in the line above.

**Comment by lewa-j** [comment]
Would you like to check other axes?

**Comment by Fronkln** [comment]
Doing it right now

> Would you like to check other axes?

**Comment by Fronkln** [comment]
We need to flip X as well, flipping Z is not necessary as far as i have seen and breaks the angles.

image
image

Followup commit incoming

**Comment by lewa-j** [comment]
Thank you

**Comment by Fronkln** [comment]
That being said, i'll definitely do more extensive tests about angles in the future and follow up with commits if i fucked anything up. 
But what i do know is the current angle rotation we have is more accurate at the **very least**

**Pull request merged**
